import duckdb
import json
import os

def profile_data():
    print("Connecting to DuckDB for S2 Profiling...")
    con = duckdb.connect()
    
    # Read the schema generated by S1
    with open('contracts/schema.json', 'r') as f:
        schema = json.load(f)
        
    cols = [col for col in schema["columns"].keys() if col != "col_time"]
    
    profiles = {}
    
    # We query the partitioned Parquet features
    print("Calculating statistics on the stratified sample...")
    
    for col in cols:
        print(f"Profiling {col}...")
        
        # We compute advanced stats including noise (std dev of diffs) and plateaus
        query = f"""
        WITH lagged AS (
            SELECT 
                {col} as val,
                {col} - lag({col}) OVER (PARTITION BY simulationRun ORDER BY col_time) as diff
            FROM 'data/features/*/*.parquet'
        )
        SELECT 
            avg(val) as mean,
            stddev_pop(val) as std_dev,
            min(val) as min_val,
            max(val) as max_val,
            approx_quantile(val, 0.25) as p25,
            approx_quantile(val, 0.50) as p50,
            approx_quantile(val, 0.75) as p75,
            count(distinct val) as distinct_vals,
            kurtosis(val) as kurtosis,
            skewness(val) as skewness,
            stddev_pop(diff) as noise_level,
            (sum(CASE WHEN diff = 0 THEN 1 ELSE 0 END)::DOUBLE / count(*)) as plateau_ratio
        FROM lagged
        """
        
        df = con.execute(query).df()
        row = df.iloc[0]
        
        profiles[col] = {
            "statistics": {
                "mean": float(row["mean"]) if not df["mean"].isnull().iloc[0] else 0.0,
                "std_dev": float(row["std_dev"]) if not df["std_dev"].isnull().iloc[0] else 0.0,
                "quantiles": {
                    "p25": float(row["p25"]) if not df["p25"].isnull().iloc[0] else 0.0,
                    "p50": float(row["p50"]) if not df["p50"].isnull().iloc[0] else 0.0,
                    "p75": float(row["p75"]) if not df["p75"].isnull().iloc[0] else 0.0
                },
                "skewness": float(row["skewness"]) if not df["skewness"].isnull().iloc[0] else 0.0,
                "distinct_values": int(row["distinct_vals"]),
                "noise_level": float(row["noise_level"]) if not df["noise_level"].isnull().iloc[0] else 0.0,
                "plateau_ratio": float(row["plateau_ratio"]) if not df["plateau_ratio"].isnull().iloc[0] else 0.0,
                "has_plateaus": bool(row["plateau_ratio"] > 0.05) if not df["plateau_ratio"].isnull().iloc[0] else False
            },
            "evidence_ids": {
                "mean": f"ev_s2_{col}_mean",
                "std_dev": f"ev_s2_{col}_stddev",
                "distribution": f"ev_s2_{col}_dist",
                "dynamics": f"ev_s2_{col}_dyn"
            }
        }
        
    os.makedirs('contracts', exist_ok=True)
    with open('contracts/profiles.json', 'w') as f:
        json.dump(profiles, f, indent=2)
        
    print("S2 Profiling complete. profiles.json generated in contracts folder.")

if __name__ == "__main__":
    profile_data()
